;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_SPRITE
	.export		_SPRITE_MOVE

; ---------------------------------------------------------------
; void __near__ SPRITE (unsigned char n, unsigned char *data, unsigned int x, unsigned char y, unsigned char color)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_SPRITE: near

.segment	"CODE"

	jsr     pusha
	ldy     #$06
	lda     (sp),y
	tay
	lda     #$01
	ldx     #$00
	jsr     aslaxy
	sta     M0002
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	jsr     aslax4
	jsr     aslax2
	sta     ptr1
	stx     ptr1+1
	clc
	lda     ptr1
	sta     M0003
	lda     #$4C
	adc     ptr1+1
	sta     M0003+1
	lda     #$00
	sta     M0001
L000F:	lda     M0001
	cmp     #$40
	bcs     L0003
	lda     M0003
	ldx     M0003+1
	clc
	adc     M0001
	bcc     L0008
	inx
L0008:	sta     sreg
	stx     sreg+1
	ldy     #$05
	jsr     ldaxysp
	ldy     M0001
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	ldy     #$00
	sta     (sreg),y
	inc     M0001
	jmp     L000F
L0003:	ldx     #$4B
	lda     #$F8
	clc
	ldy     #$06
	adc     (sp),y
	bcc     L000C
	inx
L000C:	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (sp),y
	ldy     #$30
	jsr     incaxy
	ldy     #$00
	sta     (ptr1),y
	lda     M0002
	eor     #$FF
	and     $D01C
	sta     $D01C
	ldx     #$D0
	lda     #$27
	clc
	ldy     #$06
	adc     (sp),y
	bcc     L000D
	inx
L000D:	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (sp),y
	sta     (ptr1),y
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L000A
	inx
L000A:	sta     ptr1
	stx     ptr1+1
	clc
	lda     ptr1
	sta     ptr1
	lda     #$D0
	adc     ptr1+1
	sta     ptr1+1
	ldy     #$02
	lda     (sp),y
	ldy     #$00
	sta     (ptr1),y
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L000B
	inx
L000B:	sta     ptr1
	stx     ptr1+1
	lda     #$01
	clc
	adc     ptr1
	sta     ptr1
	lda     #$D0
	adc     ptr1+1
	sta     ptr1+1
	ldy     #$01
	lda     (sp),y
	dey
	sta     (ptr1),y
	ldy     #$03
	jsr     ldaxysp
	cmp     #$00
	txa
	sbc     #$01
	bcc     L0010
	lda     M0002
	ora     $D010
	jmp     L0012
L0010:	lda     M0002
	eor     #$FF
	and     $D010
L0012:	sta     $D010
	lda     M0002
	ora     $D015
	sta     $D015
	jmp     incsp7

.segment	"BSS"

M0001:
	.res	1,$00
M0002:
	.res	1,$00
M0003:
	.res	2,$00

.endproc

; ---------------------------------------------------------------
; void __near__ SPRITE_MOVE (unsigned char n, unsigned int x, unsigned char y)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_SPRITE_MOVE: near

.segment	"CODE"

	jsr     pusha
	ldy     #$03
	lda     (sp),y
	tay
	lda     #$01
	ldx     #$00
	jsr     aslaxy
	sta     M0001
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L0004
	inx
L0004:	sta     ptr1
	stx     ptr1+1
	clc
	lda     ptr1
	sta     ptr1
	lda     #$D0
	adc     ptr1+1
	sta     ptr1+1
	ldy     #$01
	lda     (sp),y
	dey
	sta     (ptr1),y
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L0005
	inx
L0005:	sta     ptr1
	stx     ptr1+1
	lda     #$01
	clc
	adc     ptr1
	sta     ptr1
	lda     #$D0
	adc     ptr1+1
	sta     ptr1+1
	ldy     #$00
	lda     (sp),y
	sta     (ptr1),y
	ldy     #$02
	jsr     ldaxysp
	cmp     #$00
	txa
	sbc     #$01
	bcc     L0007
	lda     M0001
	ora     $D010
	jmp     L0009
L0007:	lda     M0001
	eor     #$FF
	and     $D010
L0009:	sta     $D010
	jmp     incsp4

.segment	"BSS"

M0001:
	.res	1,$00

.endproc

